name: Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Run linting
      run: uv run ruff check

    - name: Run formatting check
      run: uv run ruff format --check

    - name: Run type checking
      run: uv run mypy clickup/

    - name: Run tests
      run: uv run pytest --cov=clickup --cov-report=xml --cov-report=term-missing